# Generated by Django 4.0.3 on 2022-03-17 12:56

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='new user', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('identifier', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[accounts.models.validate_id], verbose_name='id')),
                ('biography', models.CharField(blank=True, max_length=200, verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
